// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package vo

import model "ruoyi-go-vue-plus/internal/system/model"

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertToSysClientVo(source *model.SysClient) *SysClientVo {
	var pVoSysClientVo *SysClientVo
	if source != nil {
		var voSysClientVo SysClientVo
		voSysClientVo.ID = (*source).ID
		voSysClientVo.ClientID = (*source).ClientID
		voSysClientVo.ClientKey = (*source).ClientKey
		voSysClientVo.ClientSecret = (*source).ClientSecret
		voSysClientVo.GrantType = (*source).GrantType
		voSysClientVo.DeviceType = (*source).DeviceType
		voSysClientVo.AccessPath = (*source).AccessPath
		voSysClientVo.IPWhitelist = (*source).IPWhitelist
		voSysClientVo.ActiveTimeout = (*source).ActiveTimeout
		voSysClientVo.Timeout = (*source).Timeout
		voSysClientVo.Status = (*source).Status
		pVoSysClientVo = &voSysClientVo
	}
	return pVoSysClientVo
}
func (c *ConverterImpl) ConvertToSysClientVoList(source []*model.SysClient) []*SysClientVo {
	var pVoSysClientVoList []*SysClientVo
	if source != nil {
		pVoSysClientVoList = make([]*SysClientVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysClientVoList[i] = c.ConvertToSysClientVo(source[i])
		}
	}
	return pVoSysClientVoList
}
func (c *ConverterImpl) ConvertToSysConfigVo(source *model.SysConfig) *SysConfigVo {
	var pVoSysConfigVo *SysConfigVo
	if source != nil {
		var voSysConfigVo SysConfigVo
		voSysConfigVo.ConfigID = (*source).ConfigID
		voSysConfigVo.ConfigName = (*source).ConfigName
		voSysConfigVo.ConfigKey = (*source).ConfigKey
		voSysConfigVo.ConfigValue = (*source).ConfigValue
		voSysConfigVo.ConfigType = (*source).ConfigType
		voSysConfigVo.Remark = (*source).Remark
		voSysConfigVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysConfigVo = &voSysConfigVo
	}
	return pVoSysConfigVo
}
func (c *ConverterImpl) ConvertToSysConfigVoList(source []*model.SysConfig) []*SysConfigVo {
	var pVoSysConfigVoList []*SysConfigVo
	if source != nil {
		pVoSysConfigVoList = make([]*SysConfigVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysConfigVoList[i] = c.ConvertToSysConfigVo(source[i])
		}
	}
	return pVoSysConfigVoList
}
func (c *ConverterImpl) ConvertToSysDeptVo(source *model.SysDept) *SysDeptVo {
	var pVoSysDeptVo *SysDeptVo
	if source != nil {
		var voSysDeptVo SysDeptVo
		voSysDeptVo.DeptID = (*source).DeptID
		voSysDeptVo.ParentID = (*source).ParentID
		voSysDeptVo.Ancestors = (*source).Ancestors
		voSysDeptVo.DeptName = (*source).DeptName
		voSysDeptVo.DeptCategory = (*source).DeptCategory
		voSysDeptVo.OrderNum = (*source).OrderNum
		voSysDeptVo.Leader = (*source).Leader
		voSysDeptVo.Phone = (*source).Phone
		voSysDeptVo.Email = (*source).Email
		voSysDeptVo.Status = (*source).Status
		voSysDeptVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysDeptVo = &voSysDeptVo
	}
	return pVoSysDeptVo
}
func (c *ConverterImpl) ConvertToSysDeptVoList(source []*model.SysDept) []*SysDeptVo {
	var pVoSysDeptVoList []*SysDeptVo
	if source != nil {
		pVoSysDeptVoList = make([]*SysDeptVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysDeptVoList[i] = c.ConvertToSysDeptVo(source[i])
		}
	}
	return pVoSysDeptVoList
}
func (c *ConverterImpl) ConvertToSysDictDataVo(source *model.SysDictData) *SysDictDataVo {
	var pVoSysDictDataVo *SysDictDataVo
	if source != nil {
		var voSysDictDataVo SysDictDataVo
		voSysDictDataVo.DictCode = (*source).DictCode
		voSysDictDataVo.DictSort = (*source).DictSort
		voSysDictDataVo.DictLabel = (*source).DictLabel
		voSysDictDataVo.DictValue = (*source).DictValue
		voSysDictDataVo.DictType = (*source).DictType
		voSysDictDataVo.CssClass = (*source).CssClass
		voSysDictDataVo.ListClass = (*source).ListClass
		voSysDictDataVo.IsDefault = (*source).IsDefault
		voSysDictDataVo.Remark = (*source).Remark
		voSysDictDataVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysDictDataVo = &voSysDictDataVo
	}
	return pVoSysDictDataVo
}
func (c *ConverterImpl) ConvertToSysDictDataVoList(source []*model.SysDictData) []*SysDictDataVo {
	var pVoSysDictDataVoList []*SysDictDataVo
	if source != nil {
		pVoSysDictDataVoList = make([]*SysDictDataVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysDictDataVoList[i] = c.ConvertToSysDictDataVo(source[i])
		}
	}
	return pVoSysDictDataVoList
}
func (c *ConverterImpl) ConvertToSysDictTypeVo(source *model.SysDictType) *SysDictTypeVo {
	var pVoSysDictTypeVo *SysDictTypeVo
	if source != nil {
		var voSysDictTypeVo SysDictTypeVo
		voSysDictTypeVo.DictID = (*source).DictID
		voSysDictTypeVo.DictName = (*source).DictName
		voSysDictTypeVo.DictType = (*source).DictType
		voSysDictTypeVo.Remark = (*source).Remark
		voSysDictTypeVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysDictTypeVo = &voSysDictTypeVo
	}
	return pVoSysDictTypeVo
}
func (c *ConverterImpl) ConvertToSysDictTypeVoList(source []*model.SysDictType) []*SysDictTypeVo {
	var pVoSysDictTypeVoList []*SysDictTypeVo
	if source != nil {
		pVoSysDictTypeVoList = make([]*SysDictTypeVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysDictTypeVoList[i] = c.ConvertToSysDictTypeVo(source[i])
		}
	}
	return pVoSysDictTypeVoList
}
func (c *ConverterImpl) ConvertToSysLoginInfoVo(source *model.SysLoginInfo) *SysLoginInfoVo {
	var pVoSysLoginInfoVo *SysLoginInfoVo
	if source != nil {
		var voSysLoginInfoVo SysLoginInfoVo
		voSysLoginInfoVo.InfoID = (*source).InfoID
		voSysLoginInfoVo.UserName = (*source).UserName
		voSysLoginInfoVo.ClientKey = (*source).ClientKey
		voSysLoginInfoVo.DeviceType = (*source).DeviceType
		voSysLoginInfoVo.Status = (*source).Status
		voSysLoginInfoVo.IPAddr = (*source).IPAddr
		voSysLoginInfoVo.LoginLocation = (*source).LoginLocation
		voSysLoginInfoVo.Browser = (*source).Browser
		voSysLoginInfoVo.OS = (*source).OS
		voSysLoginInfoVo.Msg = (*source).Msg
		voSysLoginInfoVo.LoginTime = (*source).LoginTime
		pVoSysLoginInfoVo = &voSysLoginInfoVo
	}
	return pVoSysLoginInfoVo
}
func (c *ConverterImpl) ConvertToSysLoginInfoVoList(source []*model.SysLoginInfo) []*SysLoginInfoVo {
	var pVoSysLoginInfoVoList []*SysLoginInfoVo
	if source != nil {
		pVoSysLoginInfoVoList = make([]*SysLoginInfoVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysLoginInfoVoList[i] = c.ConvertToSysLoginInfoVo(source[i])
		}
	}
	return pVoSysLoginInfoVoList
}
func (c *ConverterImpl) ConvertToSysMenuVo(source *model.SysMenu) *SysMenuVo {
	var pVoSysMenuVo *SysMenuVo
	if source != nil {
		var voSysMenuVo SysMenuVo
		voSysMenuVo.MenuID = (*source).MenuID
		voSysMenuVo.MenuName = (*source).MenuName
		voSysMenuVo.ParentID = (*source).ParentID
		voSysMenuVo.OrderNum = (*source).OrderNum
		voSysMenuVo.Path = (*source).Path
		voSysMenuVo.Component = (*source).Component
		voSysMenuVo.QueryParam = (*source).QueryParam
		voSysMenuVo.IsFrame = (*source).IsFrame
		voSysMenuVo.IsCache = (*source).IsCache
		voSysMenuVo.MenuType = (*source).MenuType
		voSysMenuVo.Visible = (*source).Visible
		voSysMenuVo.Status = (*source).Status
		voSysMenuVo.Perms = (*source).Perms
		voSysMenuVo.Icon = (*source).Icon
		voSysMenuVo.ActiveMenu = (*source).ActiveMenu
		voSysMenuVo.Ext = (*source).Ext
		voSysMenuVo.CreateDept = (*source).BaseEntity.CreateDept
		voSysMenuVo.Remark = (*source).Remark
		voSysMenuVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysMenuVo = &voSysMenuVo
	}
	return pVoSysMenuVo
}
func (c *ConverterImpl) ConvertToSysMenuVoList(source []*model.SysMenu) []*SysMenuVo {
	var pVoSysMenuVoList []*SysMenuVo
	if source != nil {
		pVoSysMenuVoList = make([]*SysMenuVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysMenuVoList[i] = c.ConvertToSysMenuVo(source[i])
		}
	}
	return pVoSysMenuVoList
}
func (c *ConverterImpl) ConvertToSysMessageVo(source *model.SysMessage) *SysMessageVo {
	var pVoSysMessageVo *SysMessageVo
	if source != nil {
		var voSysMessageVo SysMessageVo
		voSysMessageVo.MessageID = (*source).MessageID
		voSysMessageVo.Category = (*source).Category
		voSysMessageVo.Type = (*source).Type
		voSysMessageVo.Source = (*source).Source
		voSysMessageVo.Title = (*source).Title
		voSysMessageVo.Message = (*source).Message
		voSysMessageVo.Content = (*source).Content
		voSysMessageVo.Path = (*source).Path
		voSysMessageVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysMessageVo = &voSysMessageVo
	}
	return pVoSysMessageVo
}
func (c *ConverterImpl) ConvertToSysMessageVoList(source []*model.SysMessage) []*SysMessageVo {
	var pVoSysMessageVoList []*SysMessageVo
	if source != nil {
		pVoSysMessageVoList = make([]*SysMessageVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysMessageVoList[i] = c.ConvertToSysMessageVo(source[i])
		}
	}
	return pVoSysMessageVoList
}
func (c *ConverterImpl) ConvertToSysNoticeVo(source *model.SysNotice) *SysNoticeVo {
	var pVoSysNoticeVo *SysNoticeVo
	if source != nil {
		var voSysNoticeVo SysNoticeVo
		voSysNoticeVo.NoticeID = (*source).NoticeID
		voSysNoticeVo.NoticeTitle = (*source).NoticeTitle
		voSysNoticeVo.NoticeType = (*source).NoticeType
		voSysNoticeVo.NoticeContent = (*source).NoticeContent
		voSysNoticeVo.Status = (*source).Status
		voSysNoticeVo.Remark = (*source).Remark
		voSysNoticeVo.CreateBy = (*source).BaseEntity.CreateBy
		voSysNoticeVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysNoticeVo = &voSysNoticeVo
	}
	return pVoSysNoticeVo
}
func (c *ConverterImpl) ConvertToSysNoticeVoList(source []*model.SysNotice) []*SysNoticeVo {
	var pVoSysNoticeVoList []*SysNoticeVo
	if source != nil {
		pVoSysNoticeVoList = make([]*SysNoticeVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysNoticeVoList[i] = c.ConvertToSysNoticeVo(source[i])
		}
	}
	return pVoSysNoticeVoList
}
func (c *ConverterImpl) ConvertToSysOperLogVo(source *model.SysOperLog) *SysOperLogVo {
	var pVoSysOperLogVo *SysOperLogVo
	if source != nil {
		var voSysOperLogVo SysOperLogVo
		voSysOperLogVo.OperID = (*source).OperID
		voSysOperLogVo.Title = (*source).Title
		voSysOperLogVo.BusinessType = (*source).BusinessType
		voSysOperLogVo.Method = (*source).Method
		voSysOperLogVo.RequestMethod = (*source).RequestMethod
		voSysOperLogVo.OperatorType = (*source).OperatorType
		voSysOperLogVo.OperName = (*source).OperName
		voSysOperLogVo.UserID = (*source).UserID
		voSysOperLogVo.DeptID = (*source).DeptID
		voSysOperLogVo.DeptName = (*source).DeptName
		voSysOperLogVo.ClientKey = (*source).ClientKey
		voSysOperLogVo.DeviceType = (*source).DeviceType
		voSysOperLogVo.Browser = (*source).Browser
		voSysOperLogVo.OS = (*source).OS
		voSysOperLogVo.OperURL = (*source).OperURL
		voSysOperLogVo.OperIP = (*source).OperIP
		voSysOperLogVo.OperLocation = (*source).OperLocation
		voSysOperLogVo.OperParam = (*source).OperParam
		voSysOperLogVo.JSONResult = (*source).JSONResult
		voSysOperLogVo.Status = (*source).Status
		voSysOperLogVo.ErrorMsg = (*source).ErrorMsg
		voSysOperLogVo.OperTime = (*source).OperTime
		voSysOperLogVo.CostTime = (*source).CostTime
		pVoSysOperLogVo = &voSysOperLogVo
	}
	return pVoSysOperLogVo
}
func (c *ConverterImpl) ConvertToSysOperLogVoList(source []*model.SysOperLog) []*SysOperLogVo {
	var pVoSysOperLogVoList []*SysOperLogVo
	if source != nil {
		pVoSysOperLogVoList = make([]*SysOperLogVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysOperLogVoList[i] = c.ConvertToSysOperLogVo(source[i])
		}
	}
	return pVoSysOperLogVoList
}
func (c *ConverterImpl) ConvertToSysOssConfigVo(source *model.SysOssConfig) *SysOssConfigVo {
	var pVoSysOssConfigVo *SysOssConfigVo
	if source != nil {
		var voSysOssConfigVo SysOssConfigVo
		voSysOssConfigVo.OssConfigID = (*source).OssConfigID
		voSysOssConfigVo.ConfigKey = (*source).ConfigKey
		voSysOssConfigVo.AccessKey = (*source).AccessKey
		voSysOssConfigVo.SecretKey = (*source).SecretKey
		voSysOssConfigVo.BucketName = (*source).BucketName
		voSysOssConfigVo.Prefix = (*source).Prefix
		voSysOssConfigVo.Endpoint = (*source).Endpoint
		voSysOssConfigVo.DomainURL = (*source).DomainURL
		voSysOssConfigVo.IsHttps = (*source).IsHttps
		voSysOssConfigVo.Region = (*source).Region
		voSysOssConfigVo.Status = (*source).Status
		voSysOssConfigVo.Ext1 = (*source).Ext1
		voSysOssConfigVo.Remark = (*source).Remark
		voSysOssConfigVo.AccessPolicy = (*source).AccessPolicy
		pVoSysOssConfigVo = &voSysOssConfigVo
	}
	return pVoSysOssConfigVo
}
func (c *ConverterImpl) ConvertToSysOssConfigVoList(source []*model.SysOssConfig) []*SysOssConfigVo {
	var pVoSysOssConfigVoList []*SysOssConfigVo
	if source != nil {
		pVoSysOssConfigVoList = make([]*SysOssConfigVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysOssConfigVoList[i] = c.ConvertToSysOssConfigVo(source[i])
		}
	}
	return pVoSysOssConfigVoList
}
func (c *ConverterImpl) ConvertToSysOssVo(source *model.SysOss) *SysOssVo {
	var pVoSysOssVo *SysOssVo
	if source != nil {
		var voSysOssVo SysOssVo
		voSysOssVo.OssID = (*source).OssID
		voSysOssVo.FileName = (*source).FileName
		voSysOssVo.OriginalName = (*source).OriginalName
		voSysOssVo.FileSuffix = (*source).FileSuffix
		voSysOssVo.URL = (*source).URL
		voSysOssVo.Ext1 = (*source).Ext1
		voSysOssVo.CreateTime = (*source).BaseEntity.CreateTime
		voSysOssVo.CreateBy = (*source).BaseEntity.CreateBy
		voSysOssVo.Service = (*source).Service
		pVoSysOssVo = &voSysOssVo
	}
	return pVoSysOssVo
}
func (c *ConverterImpl) ConvertToSysOssVoList(source []*model.SysOss) []*SysOssVo {
	var pVoSysOssVoList []*SysOssVo
	if source != nil {
		pVoSysOssVoList = make([]*SysOssVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysOssVoList[i] = c.ConvertToSysOssVo(source[i])
		}
	}
	return pVoSysOssVoList
}
func (c *ConverterImpl) ConvertToSysPostVo(source *model.SysPost) *SysPostVo {
	var pVoSysPostVo *SysPostVo
	if source != nil {
		var voSysPostVo SysPostVo
		voSysPostVo.PostID = (*source).PostID
		voSysPostVo.DeptID = (*source).DeptID
		voSysPostVo.PostCode = (*source).PostCode
		voSysPostVo.PostName = (*source).PostName
		voSysPostVo.PostCategory = (*source).PostCategory
		voSysPostVo.PostSort = (*source).PostSort
		voSysPostVo.Status = (*source).Status
		voSysPostVo.Remark = (*source).Remark
		voSysPostVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysPostVo = &voSysPostVo
	}
	return pVoSysPostVo
}
func (c *ConverterImpl) ConvertToSysPostVoList(source []*model.SysPost) []*SysPostVo {
	var pVoSysPostVoList []*SysPostVo
	if source != nil {
		pVoSysPostVoList = make([]*SysPostVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysPostVoList[i] = c.ConvertToSysPostVo(source[i])
		}
	}
	return pVoSysPostVoList
}
func (c *ConverterImpl) ConvertToSysRoleVo(source *model.SysRole) *SysRoleVo {
	var pVoSysRoleVo *SysRoleVo
	if source != nil {
		var voSysRoleVo SysRoleVo
		voSysRoleVo.RoleID = (*source).RoleID
		voSysRoleVo.RoleName = (*source).RoleName
		voSysRoleVo.RoleKey = (*source).RoleKey
		voSysRoleVo.RoleSort = (*source).RoleSort
		voSysRoleVo.DataScope = (*source).DataScope
		voSysRoleVo.MenuCheckStrictly = (*source).MenuCheckStrictly
		voSysRoleVo.DeptCheckStrictly = (*source).DeptCheckStrictly
		voSysRoleVo.Status = (*source).Status
		voSysRoleVo.Remark = (*source).Remark
		voSysRoleVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysRoleVo = &voSysRoleVo
	}
	return pVoSysRoleVo
}
func (c *ConverterImpl) ConvertToSysRoleVoList(source []*model.SysRole) []*SysRoleVo {
	var pVoSysRoleVoList []*SysRoleVo
	if source != nil {
		pVoSysRoleVoList = make([]*SysRoleVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysRoleVoList[i] = c.ConvertToSysRoleVo(source[i])
		}
	}
	return pVoSysRoleVoList
}
func (c *ConverterImpl) ConvertToSysSocialVo(source *model.SysSocial) *SysSocialVo {
	var pVoSysSocialVo *SysSocialVo
	if source != nil {
		var voSysSocialVo SysSocialVo
		voSysSocialVo.ID = (*source).ID
		voSysSocialVo.UserID = (*source).UserID
		voSysSocialVo.AuthID = (*source).AuthID
		voSysSocialVo.Source = (*source).Source
		voSysSocialVo.AccessToken = (*source).AccessToken
		voSysSocialVo.ExpireIn = (*source).ExpireIn
		voSysSocialVo.RefreshToken = (*source).RefreshToken
		voSysSocialVo.OpenID = (*source).OpenID
		voSysSocialVo.UserName = (*source).UserName
		voSysSocialVo.NickName = (*source).NickName
		voSysSocialVo.Email = (*source).Email
		voSysSocialVo.Avatar = (*source).Avatar
		voSysSocialVo.AccessCode = (*source).AccessCode
		voSysSocialVo.UnionID = (*source).UnionID
		voSysSocialVo.Scope = (*source).Scope
		voSysSocialVo.TokenType = (*source).TokenType
		voSysSocialVo.IDToken = (*source).IDToken
		voSysSocialVo.MacAlgorithm = (*source).MacAlgorithm
		voSysSocialVo.MacKey = (*source).MacKey
		voSysSocialVo.Code = (*source).Code
		voSysSocialVo.OauthToken = (*source).OauthToken
		voSysSocialVo.OauthTokenSecret = (*source).OauthTokenSecret
		voSysSocialVo.CreateTime = (*source).BaseEntity.CreateTime
		pVoSysSocialVo = &voSysSocialVo
	}
	return pVoSysSocialVo
}
func (c *ConverterImpl) ConvertToSysSocialVoList(source []*model.SysSocial) []*SysSocialVo {
	var pVoSysSocialVoList []*SysSocialVo
	if source != nil {
		pVoSysSocialVoList = make([]*SysSocialVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysSocialVoList[i] = c.ConvertToSysSocialVo(source[i])
		}
	}
	return pVoSysSocialVoList
}
func (c *ConverterImpl) ConvertToSysUserExportVo(source *model.SysUser) *SysUserExportVo {
	var pVoSysUserExportVo *SysUserExportVo
	if source != nil {
		var voSysUserExportVo SysUserExportVo
		voSysUserExportVo.UserID = (*source).UserID
		voSysUserExportVo.UserName = (*source).UserName
		voSysUserExportVo.DeptID = (*source).DeptID
		voSysUserExportVo.NickName = (*source).NickName
		voSysUserExportVo.Email = (*source).Email
		voSysUserExportVo.PhoneNumber = (*source).PhoneNumber
		voSysUserExportVo.Gender = (*source).Gender
		voSysUserExportVo.Status = (*source).Status
		voSysUserExportVo.LoginIP = (*source).LoginIP
		voSysUserExportVo.LoginDate = (*source).LoginDate
		pVoSysUserExportVo = &voSysUserExportVo
	}
	return pVoSysUserExportVo
}
func (c *ConverterImpl) ConvertToSysUserExportVoList(source []*model.SysUser) []*SysUserExportVo {
	var pVoSysUserExportVoList []*SysUserExportVo
	if source != nil {
		pVoSysUserExportVoList = make([]*SysUserExportVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysUserExportVoList[i] = c.ConvertToSysUserExportVo(source[i])
		}
	}
	return pVoSysUserExportVoList
}
func (c *ConverterImpl) ConvertToSysUserVo(source *model.SysUser) *SysUserVo {
	var pVoSysUserVo *SysUserVo
	if source != nil {
		var voSysUserVo SysUserVo
		voSysUserVo.UserID = (*source).UserID
		voSysUserVo.DeptID = (*source).DeptID
		voSysUserVo.UserName = (*source).UserName
		voSysUserVo.NickName = (*source).NickName
		voSysUserVo.UserType = (*source).UserType
		voSysUserVo.Email = (*source).Email
		voSysUserVo.PhoneNumber = (*source).PhoneNumber
		voSysUserVo.Gender = (*source).Gender
		voSysUserVo.Avatar = (*source).Avatar
		voSysUserVo.Password = (*source).Password
		voSysUserVo.Status = (*source).Status
		voSysUserVo.LoginIP = (*source).LoginIP
		voSysUserVo.LoginDate = (*source).LoginDate
		voSysUserVo.Remark = (*source).Remark
		voSysUserVo.CreateTime = (*source).BaseEntity.CreateTime
		voSysUserVo.UpdateTime = (*source).BaseEntity.UpdateTime
		pVoSysUserVo = &voSysUserVo
	}
	return pVoSysUserVo
}
func (c *ConverterImpl) ConvertToSysUserVoList(source []*model.SysUser) []*SysUserVo {
	var pVoSysUserVoList []*SysUserVo
	if source != nil {
		pVoSysUserVoList = make([]*SysUserVo, len(source))
		for i := 0; i < len(source); i++ {
			pVoSysUserVoList[i] = c.ConvertToSysUserVo(source[i])
		}
	}
	return pVoSysUserVoList
}
