// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package bo

import model "ruoyi-go-vue-plus/internal/resource/model"

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertToSysOss(source *SysOssBo) *model.SysOss {
	var pModelSysOss *model.SysOss
	if source != nil {
		var modelSysOss model.SysOss
		modelSysOss.OssID = (*source).OssID
		modelSysOss.FileName = (*source).FileName
		modelSysOss.OriginalName = (*source).OriginalName
		modelSysOss.FileSuffix = (*source).FileSuffix
		modelSysOss.URL = (*source).URL
		modelSysOss.Ext1 = (*source).Ext1
		modelSysOss.Service = (*source).Service
		modelSysOss.BaseEntity = c.boSysOssBoToModelBaseEntity((*source))
		pModelSysOss = &modelSysOss
	}
	return pModelSysOss
}
func (c *ConverterImpl) ConvertToSysOssConfig(source *SysOssConfigBo) *model.SysOssConfig {
	var pModelSysOssConfig *model.SysOssConfig
	if source != nil {
		var modelSysOssConfig model.SysOssConfig
		modelSysOssConfig.OssConfigID = (*source).OssConfigID
		modelSysOssConfig.ConfigKey = (*source).ConfigKey
		modelSysOssConfig.AccessKey = (*source).AccessKey
		modelSysOssConfig.SecretKey = (*source).SecretKey
		modelSysOssConfig.BucketName = (*source).BucketName
		modelSysOssConfig.Prefix = (*source).Prefix
		modelSysOssConfig.Endpoint = (*source).Endpoint
		modelSysOssConfig.DomainURL = (*source).DomainURL
		modelSysOssConfig.IsHttps = (*source).IsHttps
		modelSysOssConfig.Region = (*source).Region
		modelSysOssConfig.Status = (*source).Status
		modelSysOssConfig.Ext1 = (*source).Ext1
		modelSysOssConfig.Remark = (*source).Remark
		modelSysOssConfig.AccessPolicy = (*source).AccessPolicy
		pModelSysOssConfig = &modelSysOssConfig
	}
	return pModelSysOssConfig
}
func (c *ConverterImpl) ConvertToSysOssConfigList(source []*SysOssConfigBo) []*model.SysOssConfig {
	var pModelSysOssConfigList []*model.SysOssConfig
	if source != nil {
		pModelSysOssConfigList = make([]*model.SysOssConfig, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysOssConfigList[i] = c.ConvertToSysOssConfig(source[i])
		}
	}
	return pModelSysOssConfigList
}
func (c *ConverterImpl) ConvertToSysOssList(source []*SysOssBo) []*model.SysOss {
	var pModelSysOssList []*model.SysOss
	if source != nil {
		pModelSysOssList = make([]*model.SysOss, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysOssList[i] = c.ConvertToSysOss(source[i])
		}
	}
	return pModelSysOssList
}
func (c *ConverterImpl) boSysOssBoToModelBaseEntity(source SysOssBo) model.BaseEntity {
	var modelBaseEntity model.BaseEntity
	modelBaseEntity.CreateBy = source.CreateBy
	return modelBaseEntity
}
