// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package bo

import model "ruoyi-go-vue-plus/internal/system/model"

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertToSysClient(source *SysClientBo) *model.SysClient {
	var pModelSysClient *model.SysClient
	if source != nil {
		var modelSysClient model.SysClient
		modelSysClient.ID = (*source).ID
		modelSysClient.ClientID = (*source).ClientID
		modelSysClient.ClientKey = (*source).ClientKey
		modelSysClient.ClientSecret = (*source).ClientSecret
		modelSysClient.GrantType = (*source).GrantType
		modelSysClient.DeviceType = (*source).DeviceType
		modelSysClient.AccessPath = (*source).AccessPath
		modelSysClient.IPWhitelist = (*source).IPWhitelist
		modelSysClient.ActiveTimeout = (*source).ActiveTimeout
		modelSysClient.Timeout = (*source).Timeout
		modelSysClient.Status = (*source).Status
		pModelSysClient = &modelSysClient
	}
	return pModelSysClient
}
func (c *ConverterImpl) ConvertToSysClientList(source []*SysClientBo) []*model.SysClient {
	var pModelSysClientList []*model.SysClient
	if source != nil {
		pModelSysClientList = make([]*model.SysClient, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysClientList[i] = c.ConvertToSysClient(source[i])
		}
	}
	return pModelSysClientList
}
func (c *ConverterImpl) ConvertToSysConfig(source *SysConfigBo) *model.SysConfig {
	var pModelSysConfig *model.SysConfig
	if source != nil {
		var modelSysConfig model.SysConfig
		modelSysConfig.ConfigID = (*source).ConfigID
		modelSysConfig.ConfigName = (*source).ConfigName
		modelSysConfig.ConfigKey = (*source).ConfigKey
		modelSysConfig.ConfigValue = (*source).ConfigValue
		modelSysConfig.ConfigType = (*source).ConfigType
		modelSysConfig.Remark = (*source).Remark
		pModelSysConfig = &modelSysConfig
	}
	return pModelSysConfig
}
func (c *ConverterImpl) ConvertToSysConfigList(source []*SysConfigBo) []*model.SysConfig {
	var pModelSysConfigList []*model.SysConfig
	if source != nil {
		pModelSysConfigList = make([]*model.SysConfig, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysConfigList[i] = c.ConvertToSysConfig(source[i])
		}
	}
	return pModelSysConfigList
}
func (c *ConverterImpl) ConvertToSysDept(source *SysDeptBo) *model.SysDept {
	var pModelSysDept *model.SysDept
	if source != nil {
		var modelSysDept model.SysDept
		modelSysDept.DeptID = (*source).DeptID
		modelSysDept.ParentID = (*source).ParentID
		modelSysDept.DeptName = (*source).DeptName
		modelSysDept.DeptCategory = (*source).DeptCategory
		modelSysDept.OrderNum = (*source).OrderNum
		modelSysDept.Leader = (*source).Leader
		modelSysDept.Phone = (*source).Phone
		modelSysDept.Email = (*source).Email
		modelSysDept.Status = (*source).Status
		pModelSysDept = &modelSysDept
	}
	return pModelSysDept
}
func (c *ConverterImpl) ConvertToSysDeptList(source []*SysDeptBo) []*model.SysDept {
	var pModelSysDeptList []*model.SysDept
	if source != nil {
		pModelSysDeptList = make([]*model.SysDept, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysDeptList[i] = c.ConvertToSysDept(source[i])
		}
	}
	return pModelSysDeptList
}
func (c *ConverterImpl) ConvertToSysDictData(source *SysDictDataBo) *model.SysDictData {
	var pModelSysDictData *model.SysDictData
	if source != nil {
		var modelSysDictData model.SysDictData
		modelSysDictData.DictCode = (*source).DictCode
		modelSysDictData.DictSort = (*source).DictSort
		modelSysDictData.DictLabel = (*source).DictLabel
		modelSysDictData.DictValue = (*source).DictValue
		modelSysDictData.DictType = (*source).DictType
		modelSysDictData.CssClass = (*source).CssClass
		modelSysDictData.ListClass = (*source).ListClass
		modelSysDictData.IsDefault = (*source).IsDefault
		modelSysDictData.Remark = (*source).Remark
		modelSysDictData.BaseEntity = c.boSysDictDataBoToModelBaseEntity((*source))
		pModelSysDictData = &modelSysDictData
	}
	return pModelSysDictData
}
func (c *ConverterImpl) ConvertToSysDictDataList(source []*SysDictDataBo) []*model.SysDictData {
	var pModelSysDictDataList []*model.SysDictData
	if source != nil {
		pModelSysDictDataList = make([]*model.SysDictData, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysDictDataList[i] = c.ConvertToSysDictData(source[i])
		}
	}
	return pModelSysDictDataList
}
func (c *ConverterImpl) ConvertToSysDictType(source *SysDictTypeBo) *model.SysDictType {
	var pModelSysDictType *model.SysDictType
	if source != nil {
		var modelSysDictType model.SysDictType
		modelSysDictType.DictID = (*source).DictID
		modelSysDictType.DictName = (*source).DictName
		modelSysDictType.DictType = (*source).DictType
		modelSysDictType.Remark = (*source).Remark
		pModelSysDictType = &modelSysDictType
	}
	return pModelSysDictType
}
func (c *ConverterImpl) ConvertToSysDictTypeList(source []*SysDictTypeBo) []*model.SysDictType {
	var pModelSysDictTypeList []*model.SysDictType
	if source != nil {
		pModelSysDictTypeList = make([]*model.SysDictType, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysDictTypeList[i] = c.ConvertToSysDictType(source[i])
		}
	}
	return pModelSysDictTypeList
}
func (c *ConverterImpl) ConvertToSysLoginInfo(source *SysLoginInfoBo) *model.SysLoginInfo {
	var pModelSysLoginInfo *model.SysLoginInfo
	if source != nil {
		var modelSysLoginInfo model.SysLoginInfo
		modelSysLoginInfo.InfoID = (*source).InfoID
		modelSysLoginInfo.UserName = (*source).UserName
		modelSysLoginInfo.ClientKey = (*source).ClientKey
		modelSysLoginInfo.DeviceType = (*source).DeviceType
		modelSysLoginInfo.Status = (*source).Status
		modelSysLoginInfo.IPAddr = (*source).IPAddr
		modelSysLoginInfo.LoginLocation = (*source).LoginLocation
		modelSysLoginInfo.Browser = (*source).Browser
		modelSysLoginInfo.OS = (*source).OS
		modelSysLoginInfo.Msg = (*source).Msg
		modelSysLoginInfo.LoginTime = (*source).LoginTime
		pModelSysLoginInfo = &modelSysLoginInfo
	}
	return pModelSysLoginInfo
}
func (c *ConverterImpl) ConvertToSysLoginInfoList(source []*SysLoginInfoBo) []*model.SysLoginInfo {
	var pModelSysLoginInfoList []*model.SysLoginInfo
	if source != nil {
		pModelSysLoginInfoList = make([]*model.SysLoginInfo, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysLoginInfoList[i] = c.ConvertToSysLoginInfo(source[i])
		}
	}
	return pModelSysLoginInfoList
}
func (c *ConverterImpl) ConvertToSysMenu(source *SysMenuBo) *model.SysMenu {
	var pModelSysMenu *model.SysMenu
	if source != nil {
		var modelSysMenu model.SysMenu
		modelSysMenu.MenuID = (*source).MenuID
		modelSysMenu.ParentID = (*source).ParentID
		modelSysMenu.MenuName = (*source).MenuName
		modelSysMenu.OrderNum = (*source).OrderNum
		modelSysMenu.Path = (*source).Path
		modelSysMenu.Component = (*source).Component
		modelSysMenu.QueryParam = (*source).QueryParam
		modelSysMenu.IsFrame = (*source).IsFrame
		modelSysMenu.IsCache = (*source).IsCache
		modelSysMenu.MenuType = (*source).MenuType
		modelSysMenu.Visible = (*source).Visible
		modelSysMenu.Status = (*source).Status
		modelSysMenu.Perms = (*source).Perms
		modelSysMenu.Icon = (*source).Icon
		modelSysMenu.ActiveMenu = (*source).ActiveMenu
		modelSysMenu.Ext = (*source).Ext
		modelSysMenu.Remark = (*source).Remark
		pModelSysMenu = &modelSysMenu
	}
	return pModelSysMenu
}
func (c *ConverterImpl) ConvertToSysMenuList(source []*SysMenuBo) []*model.SysMenu {
	var pModelSysMenuList []*model.SysMenu
	if source != nil {
		pModelSysMenuList = make([]*model.SysMenu, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysMenuList[i] = c.ConvertToSysMenu(source[i])
		}
	}
	return pModelSysMenuList
}
func (c *ConverterImpl) ConvertToSysNotice(source *SysNoticeBo) *model.SysNotice {
	var pModelSysNotice *model.SysNotice
	if source != nil {
		var modelSysNotice model.SysNotice
		modelSysNotice.NoticeID = (*source).NoticeID
		modelSysNotice.NoticeTitle = (*source).NoticeTitle
		modelSysNotice.NoticeType = (*source).NoticeType
		modelSysNotice.NoticeContent = (*source).NoticeContent
		modelSysNotice.Status = (*source).Status
		modelSysNotice.Remark = (*source).Remark
		pModelSysNotice = &modelSysNotice
	}
	return pModelSysNotice
}
func (c *ConverterImpl) ConvertToSysNoticeList(source []*SysNoticeBo) []*model.SysNotice {
	var pModelSysNoticeList []*model.SysNotice
	if source != nil {
		pModelSysNoticeList = make([]*model.SysNotice, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysNoticeList[i] = c.ConvertToSysNotice(source[i])
		}
	}
	return pModelSysNoticeList
}
func (c *ConverterImpl) ConvertToSysOperLog(source *SysOperLogBo) *model.SysOperLog {
	var pModelSysOperLog *model.SysOperLog
	if source != nil {
		var modelSysOperLog model.SysOperLog
		modelSysOperLog.OperID = (*source).OperID
		modelSysOperLog.Title = (*source).Title
		modelSysOperLog.BusinessType = (*source).BusinessType
		modelSysOperLog.Method = (*source).Method
		modelSysOperLog.RequestMethod = (*source).RequestMethod
		modelSysOperLog.OperatorType = (*source).OperatorType
		modelSysOperLog.OperName = (*source).OperName
		modelSysOperLog.UserID = (*source).UserID
		modelSysOperLog.DeptID = (*source).DeptID
		modelSysOperLog.DeptName = (*source).DeptName
		modelSysOperLog.ClientKey = (*source).ClientKey
		modelSysOperLog.DeviceType = (*source).DeviceType
		modelSysOperLog.Browser = (*source).Browser
		modelSysOperLog.OS = (*source).OS
		modelSysOperLog.OperURL = (*source).OperURL
		modelSysOperLog.OperIP = (*source).OperIP
		modelSysOperLog.OperLocation = (*source).OperLocation
		modelSysOperLog.OperParam = (*source).OperParam
		modelSysOperLog.JSONResult = (*source).JSONResult
		modelSysOperLog.Status = (*source).Status
		modelSysOperLog.ErrorMsg = (*source).ErrorMsg
		modelSysOperLog.OperTime = (*source).OperTime
		modelSysOperLog.CostTime = (*source).CostTime
		pModelSysOperLog = &modelSysOperLog
	}
	return pModelSysOperLog
}
func (c *ConverterImpl) ConvertToSysOperLogList(source []*SysOperLogBo) []*model.SysOperLog {
	var pModelSysOperLogList []*model.SysOperLog
	if source != nil {
		pModelSysOperLogList = make([]*model.SysOperLog, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysOperLogList[i] = c.ConvertToSysOperLog(source[i])
		}
	}
	return pModelSysOperLogList
}
func (c *ConverterImpl) ConvertToSysOss(source *SysOssBo) *model.SysOss {
	var pModelSysOss *model.SysOss
	if source != nil {
		var modelSysOss model.SysOss
		modelSysOss.OssID = (*source).OssID
		modelSysOss.FileName = (*source).FileName
		modelSysOss.OriginalName = (*source).OriginalName
		modelSysOss.FileSuffix = (*source).FileSuffix
		modelSysOss.URL = (*source).URL
		modelSysOss.Ext1 = (*source).Ext1
		modelSysOss.Service = (*source).Service
		modelSysOss.BaseEntity = c.boSysOssBoToModelBaseEntity((*source))
		pModelSysOss = &modelSysOss
	}
	return pModelSysOss
}
func (c *ConverterImpl) ConvertToSysOssConfig(source *SysOssConfigBo) *model.SysOssConfig {
	var pModelSysOssConfig *model.SysOssConfig
	if source != nil {
		var modelSysOssConfig model.SysOssConfig
		modelSysOssConfig.OssConfigID = (*source).OssConfigID
		modelSysOssConfig.ConfigKey = (*source).ConfigKey
		modelSysOssConfig.AccessKey = (*source).AccessKey
		modelSysOssConfig.SecretKey = (*source).SecretKey
		modelSysOssConfig.BucketName = (*source).BucketName
		modelSysOssConfig.Prefix = (*source).Prefix
		modelSysOssConfig.Endpoint = (*source).Endpoint
		modelSysOssConfig.DomainURL = (*source).DomainURL
		modelSysOssConfig.IsHttps = (*source).IsHttps
		modelSysOssConfig.Region = (*source).Region
		modelSysOssConfig.Status = (*source).Status
		modelSysOssConfig.Ext1 = (*source).Ext1
		modelSysOssConfig.Remark = (*source).Remark
		modelSysOssConfig.AccessPolicy = (*source).AccessPolicy
		pModelSysOssConfig = &modelSysOssConfig
	}
	return pModelSysOssConfig
}
func (c *ConverterImpl) ConvertToSysOssConfigList(source []*SysOssConfigBo) []*model.SysOssConfig {
	var pModelSysOssConfigList []*model.SysOssConfig
	if source != nil {
		pModelSysOssConfigList = make([]*model.SysOssConfig, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysOssConfigList[i] = c.ConvertToSysOssConfig(source[i])
		}
	}
	return pModelSysOssConfigList
}
func (c *ConverterImpl) ConvertToSysOssList(source []*SysOssBo) []*model.SysOss {
	var pModelSysOssList []*model.SysOss
	if source != nil {
		pModelSysOssList = make([]*model.SysOss, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysOssList[i] = c.ConvertToSysOss(source[i])
		}
	}
	return pModelSysOssList
}
func (c *ConverterImpl) ConvertToSysPost(source *SysPostBo) *model.SysPost {
	var pModelSysPost *model.SysPost
	if source != nil {
		var modelSysPost model.SysPost
		modelSysPost.PostID = (*source).PostID
		modelSysPost.DeptID = (*source).DeptID
		modelSysPost.PostCode = (*source).PostCode
		modelSysPost.PostName = (*source).PostName
		modelSysPost.PostCategory = (*source).PostCategory
		modelSysPost.PostSort = (*source).PostSort
		modelSysPost.Status = (*source).Status
		modelSysPost.Remark = (*source).Remark
		pModelSysPost = &modelSysPost
	}
	return pModelSysPost
}
func (c *ConverterImpl) ConvertToSysPostList(source []*SysPostBo) []*model.SysPost {
	var pModelSysPostList []*model.SysPost
	if source != nil {
		pModelSysPostList = make([]*model.SysPost, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysPostList[i] = c.ConvertToSysPost(source[i])
		}
	}
	return pModelSysPostList
}
func (c *ConverterImpl) ConvertToSysRole(source *SysRoleBo) *model.SysRole {
	var pModelSysRole *model.SysRole
	if source != nil {
		var modelSysRole model.SysRole
		modelSysRole.RoleID = (*source).RoleID
		modelSysRole.RoleName = (*source).RoleName
		modelSysRole.RoleKey = (*source).RoleKey
		modelSysRole.RoleSort = (*source).RoleSort
		modelSysRole.DataScope = (*source).DataScope
		modelSysRole.MenuCheckStrictly = (*source).MenuCheckStrictly
		modelSysRole.DeptCheckStrictly = (*source).DeptCheckStrictly
		modelSysRole.Status = (*source).Status
		modelSysRole.Remark = (*source).Remark
		pModelSysRole = &modelSysRole
	}
	return pModelSysRole
}
func (c *ConverterImpl) ConvertToSysRoleList(source []*SysRoleBo) []*model.SysRole {
	var pModelSysRoleList []*model.SysRole
	if source != nil {
		pModelSysRoleList = make([]*model.SysRole, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysRoleList[i] = c.ConvertToSysRole(source[i])
		}
	}
	return pModelSysRoleList
}
func (c *ConverterImpl) ConvertToSysSocial(source *SysSocialBo) *model.SysSocial {
	var pModelSysSocial *model.SysSocial
	if source != nil {
		var modelSysSocial model.SysSocial
		modelSysSocial.ID = (*source).ID
		modelSysSocial.UserID = (*source).UserID
		modelSysSocial.AuthID = (*source).AuthID
		modelSysSocial.Source = (*source).Source
		modelSysSocial.AccessToken = (*source).AccessToken
		modelSysSocial.ExpireIn = (*source).ExpireIn
		modelSysSocial.RefreshToken = (*source).RefreshToken
		modelSysSocial.OpenID = (*source).OpenID
		modelSysSocial.UserName = (*source).UserName
		modelSysSocial.NickName = (*source).NickName
		modelSysSocial.Email = (*source).Email
		modelSysSocial.Avatar = (*source).Avatar
		modelSysSocial.AccessCode = (*source).AccessCode
		modelSysSocial.UnionID = (*source).UnionID
		modelSysSocial.Scope = (*source).Scope
		modelSysSocial.TokenType = (*source).TokenType
		modelSysSocial.IDToken = (*source).IDToken
		modelSysSocial.MacAlgorithm = (*source).MacAlgorithm
		modelSysSocial.MacKey = (*source).MacKey
		modelSysSocial.Code = (*source).Code
		modelSysSocial.OauthToken = (*source).OauthToken
		modelSysSocial.OauthTokenSecret = (*source).OauthTokenSecret
		pModelSysSocial = &modelSysSocial
	}
	return pModelSysSocial
}
func (c *ConverterImpl) ConvertToSysSocialList(source []*SysSocialBo) []*model.SysSocial {
	var pModelSysSocialList []*model.SysSocial
	if source != nil {
		pModelSysSocialList = make([]*model.SysSocial, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysSocialList[i] = c.ConvertToSysSocial(source[i])
		}
	}
	return pModelSysSocialList
}
func (c *ConverterImpl) ConvertToSysUser(source *SysUserBo) *model.SysUser {
	var pModelSysUser *model.SysUser
	if source != nil {
		var modelSysUser model.SysUser
		modelSysUser.UserID = (*source).UserID
		modelSysUser.DeptID = (*source).DeptID
		modelSysUser.UserName = (*source).UserName
		modelSysUser.NickName = (*source).NickName
		modelSysUser.UserType = (*source).UserType
		modelSysUser.Email = (*source).Email
		modelSysUser.PhoneNumber = (*source).PhoneNumber
		modelSysUser.Gender = (*source).Gender
		modelSysUser.Avatar = (*source).Avatar
		modelSysUser.Password = (*source).Password
		modelSysUser.Status = (*source).Status
		modelSysUser.Remark = (*source).Remark
		modelSysUser.BaseEntity = c.boSysUserBoToModelBaseEntity((*source))
		pModelSysUser = &modelSysUser
	}
	return pModelSysUser
}
func (c *ConverterImpl) ConvertToSysUserFromProfile(source *SysUserProfileBo) *model.SysUser {
	var pModelSysUser *model.SysUser
	if source != nil {
		var modelSysUser model.SysUser
		modelSysUser.NickName = (*source).NickName
		modelSysUser.Email = (*source).Email
		modelSysUser.PhoneNumber = (*source).PhoneNumber
		modelSysUser.Gender = (*source).Gender
		modelSysUser.Avatar = (*source).Avatar
		pModelSysUser = &modelSysUser
	}
	return pModelSysUser
}
func (c *ConverterImpl) ConvertToSysUserFromProfileList(source []*SysUserProfileBo) []*model.SysUser {
	var pModelSysUserList []*model.SysUser
	if source != nil {
		pModelSysUserList = make([]*model.SysUser, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysUserList[i] = c.ConvertToSysUserFromProfile(source[i])
		}
	}
	return pModelSysUserList
}
func (c *ConverterImpl) ConvertToSysUserList(source []*SysUserBo) []*model.SysUser {
	var pModelSysUserList []*model.SysUser
	if source != nil {
		pModelSysUserList = make([]*model.SysUser, len(source))
		for i := 0; i < len(source); i++ {
			pModelSysUserList[i] = c.ConvertToSysUser(source[i])
		}
	}
	return pModelSysUserList
}
func (c *ConverterImpl) boSysDictDataBoToModelBaseEntity(source SysDictDataBo) model.BaseEntity {
	var modelBaseEntity model.BaseEntity
	modelBaseEntity.CreateDept = source.CreateDept
	return modelBaseEntity
}
func (c *ConverterImpl) boSysOssBoToModelBaseEntity(source SysOssBo) model.BaseEntity {
	var modelBaseEntity model.BaseEntity
	modelBaseEntity.CreateBy = source.CreateBy
	return modelBaseEntity
}
func (c *ConverterImpl) boSysUserBoToModelBaseEntity(source SysUserBo) model.BaseEntity {
	var modelBaseEntity model.BaseEntity
	modelBaseEntity.CreateBy = source.CreateBy
	modelBaseEntity.UpdateBy = source.UpdateBy
	return modelBaseEntity
}
