// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package dto

import vo "ruoyi-go-vue-plus/internal/system/model/vo"

type ConverterImpl struct{}

func (c *ConverterImpl) ConvertToPostDTO(source *vo.SysPostVo) *PostDTO {
	var pDtoPostDTO *PostDTO
	if source != nil {
		var dtoPostDTO PostDTO
		dtoPostDTO.PostID = (*source).PostID
		dtoPostDTO.DeptID = (*source).DeptID
		dtoPostDTO.PostCode = (*source).PostCode
		dtoPostDTO.PostName = (*source).PostName
		dtoPostDTO.PostCategory = (*source).PostCategory
		pDtoPostDTO = &dtoPostDTO
	}
	return pDtoPostDTO
}
func (c *ConverterImpl) ConvertToPostDTOList(source []*vo.SysPostVo) []*PostDTO {
	var pDtoPostDTOList []*PostDTO
	if source != nil {
		pDtoPostDTOList = make([]*PostDTO, len(source))
		for i := 0; i < len(source); i++ {
			pDtoPostDTOList[i] = c.ConvertToPostDTO(source[i])
		}
	}
	return pDtoPostDTOList
}
func (c *ConverterImpl) ConvertToRoleDTO(source *vo.SysRoleVo) *RoleDTO {
	var pDtoRoleDTO *RoleDTO
	if source != nil {
		var dtoRoleDTO RoleDTO
		dtoRoleDTO.RoleID = (*source).RoleID
		dtoRoleDTO.RoleName = (*source).RoleName
		dtoRoleDTO.RoleKey = (*source).RoleKey
		dtoRoleDTO.DataScope = (*source).DataScope
		pDtoRoleDTO = &dtoRoleDTO
	}
	return pDtoRoleDTO
}
func (c *ConverterImpl) ConvertToRoleDTOList(source []*vo.SysRoleVo) []*RoleDTO {
	var pDtoRoleDTOList []*RoleDTO
	if source != nil {
		pDtoRoleDTOList = make([]*RoleDTO, len(source))
		for i := 0; i < len(source); i++ {
			pDtoRoleDTOList[i] = c.ConvertToRoleDTO(source[i])
		}
	}
	return pDtoRoleDTOList
}
